// packages/react/src/components.tsx
"use client"

import {
  AdrawCanvas,
  type CanvasElement,
  type CanvasEventMap,
  type CanvasOptions,
  type ElementId,
  type ToolType,
  type ViewportState,
} from "@adraw/core"
import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react"

export interface CanvasReactOptions extends CanvasOptions {}

interface CanvasContextValue {
  vanillaRef: React.RefObject<AdrawCanvas | null>
  elements: Map<ElementId, CanvasElement>
  setElements: React.Dispatch<React.SetStateAction<Map<string, CanvasElement>>>
  viewport: ViewportState
  setViewport: React.Dispatch<React.SetStateAction<ViewportState>>
  activeTool: ToolType
  setActiveTool: React.Dispatch<React.SetStateAction<ToolType>>
  selectedIds: Set<ElementId>
  setSelectedIds: React.Dispatch<React.SetStateAction<Set<string>>>
  hideWhileTransforming: boolean
  setHideWhileTransforming: React.Dispatch<React.SetStateAction<boolean>>
  options?: CanvasReactOptions
  setOptions: React.Dispatch<
    React.SetStateAction<CanvasReactOptions | undefined>
  >
}

const CanvasContext = createContext<CanvasContextValue | null>(null)

interface CanvasProviderProps {
  children: ReactNode
  options?: CanvasReactOptions
}

export function CanvasProvider({
  children,
  options: defaultOptions,
}: CanvasProviderProps) {
  const [options, setOptions] = useState<CanvasReactOptions | undefined>(
    defaultOptions,
  )
  const vanillaRef = useRef<AdrawCanvas | null>(null)
  const [elements, setElements] = useState<Map<ElementId, CanvasElement>>(
    new Map(),
  )
  const [viewport, setViewport] = useState<ViewportState>({
    x: 0,
    y: 0,
    zoom: 1,
  })
  const [activeTool, setActiveTool] = useState<ToolType>("select")
  const [selectedIds, setSelectedIds] = useState<Set<ElementId>>(new Set())
  const [hideWhileTransforming, setHideWhileTransforming] = useState<boolean>(
    defaultOptions?.hideOverlayWhileTransforming ?? true,
  )

  const value = useMemo<CanvasContextValue>(
    () => ({
      activeTool,
      elements,
      hideWhileTransforming,
      options,
      selectedIds,
      setActiveTool,
      setElements,
      setHideWhileTransforming,
      setOptions,
      setSelectedIds,
      setViewport,
      vanillaRef,
      viewport,
    }),
    [
      elements,
      viewport,
      activeTool,
      selectedIds,
      hideWhileTransforming,
      options,
    ],
  )

  return (
    <CanvasContext.Provider value={value}>{children}</CanvasContext.Provider>
  )
}

export function useCanvas() {
  const context = useContext(CanvasContext)
  if (!context) {
    throw new Error("useCanvas must be used within a CanvasProvider")
  }
  return context
}

export function useTool() {
  const { vanillaRef, activeTool, setActiveTool } = useCanvas()

  const setTool = useCallback(
    (tool: ToolType) => {
      vanillaRef?.current?.setActiveTool(tool)
      setActiveTool(tool)
    },
    [vanillaRef, setActiveTool],
  )

  return { setTool, tool: activeTool }
}

export function useViewport() {
  const { vanillaRef, viewport } = useCanvas()

  const setViewport = useCallback(
    (newViewport: ViewportState) => {
      vanillaRef?.current?.setViewport(newViewport)
    },
    [vanillaRef],
  )

  const zoomIn = useCallback(() => {
    vanillaRef?.current?.zoomIn()
  }, [vanillaRef])

  const zoomOut = useCallback(() => {
    vanillaRef?.current?.zoomOut()
  }, [vanillaRef])

  const resetZoom = useCallback(() => {
    vanillaRef?.current?.resetZoom()
  }, [vanillaRef])

  const zoomToFit = useCallback(() => {
    vanillaRef?.current?.zoomToFit()
  }, [vanillaRef])

  return {
    resetZoom,
    setViewport,
    viewport,
    zoomIn,
    zoomOut,
    zoomToFit,
  }
}

export function useHistory() {
  const { vanillaRef } = useCanvas()

  const undo = useCallback(
    () => vanillaRef?.current?.undo() ?? false,
    [vanillaRef],
  )

  const redo = useCallback(
    () => vanillaRef?.current?.redo() ?? false,
    [vanillaRef],
  )

  const canUndo = useCallback(
    () => vanillaRef?.current?.canUndo() ?? false,
    [vanillaRef],
  )

  const canRedo = useCallback(
    () => vanillaRef?.current?.canRedo() ?? false,
    [vanillaRef],
  )

  return { canRedo, canUndo, redo, undo }
}

export function useSelection() {
  const { vanillaRef, selectedIds, elements } = useCanvas()

  const selectAll = useCallback(() => {
    vanillaRef?.current?.selectAll()
  }, [vanillaRef])

  const clearSelection = useCallback(() => {
    vanillaRef?.current?.clearSelection()
  }, [vanillaRef])

  const deleteSelected = useCallback(() => {
    vanillaRef?.current?.deleteSelected()
  }, [vanillaRef])

  return {
    clearSelection,
    deleteSelected,
    elements,
    selectAll,
    selectedIds,
  }
}

export function useTransformOverlay() {
  const { vanillaRef, hideWhileTransforming, setHideWhileTransforming } =
    useCanvas()

  const setHide = useCallback(
    (hide: boolean) => {
      vanillaRef?.current?.setHideOverlayWhileTransforming(hide)
      setHideWhileTransforming(hide)
    },
    [vanillaRef, setHideWhileTransforming],
  )

  return { hideWhileTransforming, setHideWhileTransforming: setHide }
}

interface CanvasProps {
  className?: string
  style?: React.CSSProperties
}

export function Canvas({ className, style }: CanvasProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const {
    vanillaRef,
    options,
    setElements,
    setViewport,
    setActiveTool,
    setSelectedIds,
  } = useCanvas()

  useEffect(() => {
    if (!containerRef.current) {
      return
    }

    const vanilla = new AdrawCanvas({
      container: containerRef.current,
      hideOverlayWhileTransforming: options?.hideOverlayWhileTransforming,
      initialViewport: options?.initialViewport,
      snapping: options?.snapping,
    })

    vanillaRef.current = vanilla

    const core = vanilla

    core.on<"change">(
      "change",
      ({ elements: newElements }: CanvasEventMap["change"]) => {
        setElements(new Map(newElements))
      },
    )

    core.on<"viewportChange">(
      "viewportChange",
      ({ viewport: newViewport }: CanvasEventMap["viewportChange"]) => {
        setViewport(newViewport)
      },
    )

    core.on<"toolChange">(
      "toolChange",
      ({ tool }: CanvasEventMap["toolChange"]) => {
        setActiveTool(tool)
      },
    )

    core.on<"selectionChange">(
      "selectionChange",
      ({ selectedIds: newSelectedIds }: CanvasEventMap["selectionChange"]) => {
        setSelectedIds(new Set(newSelectedIds))
      },
    )

    vanilla.render()

    return () => {
      vanilla.destroy()
      vanillaRef.current = null
    }
  }, [
    options?.hideOverlayWhileTransforming,
    options?.initialViewport,
    options?.snapping,
    setActiveTool,
    setElements,
    setSelectedIds,
    setViewport,
    vanillaRef,
  ])

  return (
    <div
      ref={containerRef}
      className={className}
      style={{ height: "100%", width: "100%", ...style }}
    />
  )
}

// packages/solid/src/components.tsx
import {
  AdrawCanvas,
  type CanvasElement,
  type CanvasEventMap,
  type CanvasOptions,
  type ElementId,
  type ToolType,
  type ViewportState,
} from "@adraw/core"
import {
  createComponent,
  createContext,
  createSignal,
  onCleanup,
  onMount,
  useContext,
  type Accessor,
  type JSX,
  type Setter,
} from "solid-js"

export interface CanvasSolidOptions extends CanvasOptions {}

interface CanvasRef {
  current: AdrawCanvas | null
}

interface CanvasContextValue {
  canvasRef: CanvasRef
  elements: Accessor<Map<ElementId, CanvasElement>>
  setElements: Setter<Map<ElementId, CanvasElement>>
  viewport: Accessor<ViewportState>
  setViewport: Setter<ViewportState>
  activeTool: Accessor<ToolType>
  setActiveTool: Setter<ToolType>
  selectedIds: Accessor<Set<ElementId>>
  setSelectedIds: Setter<Set<ElementId>>
  canUndo: Accessor<boolean>
  setCanUndo: Setter<boolean>
  canRedo: Accessor<boolean>
  setCanRedo: Setter<boolean>
  hideWhileTransforming: Accessor<boolean>
  setHideWhileTransforming: Setter<boolean>
  options?: CanvasSolidOptions
}

const CanvasContext = createContext<CanvasContextValue | null>(null)

export interface CanvasProviderProps {
  children?: JSX.Element
  options?: CanvasSolidOptions
}

export function CanvasProvider(props: CanvasProviderProps): JSX.Element {
  const canvasRef: CanvasRef = { current: null }
  const [elements, setElements] = createSignal<Map<ElementId, CanvasElement>>(
    new Map(),
  )
  const [viewport, setViewport] = createSignal<ViewportState>({
    x: 0,
    y: 0,
    zoom: 1,
  })
  const [activeTool, setActiveTool] = createSignal<ToolType>("select")
  const [selectedIds, setSelectedIds] = createSignal<Set<ElementId>>(new Set())
  const [canUndo, setCanUndo] = createSignal(false)
  const [canRedo, setCanRedo] = createSignal(false)
  const [hideWhileTransforming, setHideWhileTransforming] = createSignal(
    props.options?.hideOverlayWhileTransforming ?? true,
  )

  const value: CanvasContextValue = {
    activeTool,
    canRedo,
    canUndo,
    canvasRef,
    elements,
    hideWhileTransforming,
    get options() {
      return props.options
    },
    selectedIds,
    setActiveTool,
    setCanRedo,
    setCanUndo,
    setElements,
    setHideWhileTransforming,
    setSelectedIds,
    setViewport,
    viewport,
  }

  return createComponent(CanvasContext.Provider, {
    get children() {
      return props.children
    },
    value,
  })
}

export function useCanvas() {
  const context = useContext(CanvasContext)
  if (!context) {
    throw new Error("useCanvas must be used within a CanvasProvider")
  }
  return context
}

export function useTool() {
  const { canvasRef, activeTool } = useCanvas()

  return {
    setTool: (tool: ToolType) => {
      canvasRef.current?.setActiveTool(tool)
    },
    get tool() {
      return activeTool()
    },
  }
}

export function useViewport() {
  const { canvasRef, viewport } = useCanvas()

  return {
    resetZoom: () => canvasRef.current?.resetZoom(),
    setViewport: (newViewport: ViewportState) => {
      canvasRef.current?.setViewport(newViewport)
    },
    get viewport() {
      return viewport()
    },
    zoomIn: () => canvasRef.current?.zoomIn(),
    zoomOut: () => canvasRef.current?.zoomOut(),
    zoomToFit: () => canvasRef.current?.zoomToFit(),
  }
}

export function useHistory() {
  const { canvasRef, canUndo, canRedo } = useCanvas()

  return {
    canRedo: () => canRedo(),
    canUndo: () => canUndo(),
    redo: () => canvasRef.current?.redo() ?? false,
    undo: () => canvasRef.current?.undo() ?? false,
  }
}

export function useTransformOverlay() {
  const { canvasRef, hideWhileTransforming, setHideWhileTransforming } =
    useCanvas()

  return {
    get hideWhileTransforming() {
      return hideWhileTransforming()
    },
    setHideWhileTransforming: (hide: boolean) => {
      canvasRef.current?.setHideOverlayWhileTransforming(hide)
      setHideWhileTransforming(hide)
    },
  }
}

export function useSelection() {
  const { canvasRef, selectedIds, elements } = useCanvas()

  return {
    clearSelection: () => canvasRef.current?.clearSelection(),
    deleteSelected: () => canvasRef.current?.deleteSelected(),
    get elements() {
      return elements()
    },
    selectAll: () => canvasRef.current?.selectAll(),
    get selectedIds() {
      return selectedIds()
    },
  }
}

export interface CanvasProps {
  class?: string
  style?: JSX.CSSProperties
}

export function Canvas(props: CanvasProps): JSX.Element {
  const {
    canvasRef,
    options,
    setElements,
    setViewport,
    setActiveTool,
    setSelectedIds,
    setCanUndo,
    setCanRedo,
  } = useCanvas()
  let containerRef: HTMLDivElement | undefined

  onMount(() => {
    if (!containerRef) {
      return
    }

    const canvas = new AdrawCanvas({
      container: containerRef,
      hideOverlayWhileTransforming: options?.hideOverlayWhileTransforming,
      initialViewport: options?.initialViewport,
      snapping: options?.snapping,
    })

    canvasRef.current = canvas

    // Read history availability after the current pointer/tool handler
    // finishes: tools emit "change" from setElements before calling
    // pushHistory, so canUndo/canRedo are only accurate on the next microtask.
    const syncHistory = () => {
      queueMicrotask(() => {
        setCanUndo(canvas.canUndo())
        setCanRedo(canvas.canRedo())
      })
    }

    canvas.on<"change">(
      "change",
      ({ elements: newElements }: CanvasEventMap["change"]) => {
        setElements(new Map(newElements))
        syncHistory()
      },
    )

    canvas.on<"viewportChange">(
      "viewportChange",
      ({ viewport: newViewport }: CanvasEventMap["viewportChange"]) => {
        setViewport(newViewport)
      },
    )

    canvas.on<"toolChange">(
      "toolChange",
      ({ tool }: CanvasEventMap["toolChange"]) => {
        setActiveTool(tool)
      },
    )

    canvas.on<"selectionChange">(
      "selectionChange",
      ({ selectedIds: newSelectedIds }: CanvasEventMap["selectionChange"]) => {
        setSelectedIds(new Set(newSelectedIds))
      },
    )

    canvas.render()
  })

  onCleanup(() => {
    canvasRef.current?.destroy()
    canvasRef.current = null
  })

  return (
    <div
      ref={containerRef}
      class={props.class}
      style={{ height: "100%", width: "100%", ...props.style }}
    />
  )
}
